version: "3.7"

services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ifpb
      POSTGRES_DB: athena
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data